name: Env Var and Secrets

on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, prod]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set Environment Variable
        id: set-env
        run: echo "ENVIRONMENT=${{ matrix.environment }}" >> $GITHUB_ENV

      - name: Display Environment Variable
        run: |
          echo "Building for environment: ${{ matrix.environment }}"
          echo "ENVIRONMENT_NAME: ${{ env.ENVIRONMENT }}"
          echo "ENVIRONMENT_NAME length: ${#ENVIRONMENT}"
          echo "ENVIRONMENT_NAME (partial): ${ENVIRONMENT:0:5}..."
        env:
          ENVIRONMENT: ${{ matrix.environment }}

      - name: Display Environment Secret
        run: |
          echo "SECRET length: ${#SECRET}"
        env:
          SECRET: ${{ secrets.SECRET }}

      - name: Display Repository Variable
        run: |
          echo "REPOSITORY_VARIABLE: ${{ vars.REPOSITORY_VARIABLE }}"
