name: custom workflow

on:
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a $ event."
      - run: echo "🐧 This job is now running on a $ server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is $ and your repository is $."

      - name: Check Code
        uses: actions/checkout@v4

      - run: echo "💡 The $ repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: List Files In Directory
        run: |
          ls

      - run: echo "🍏 This job's status is $."

      - name: Adding Markdown
        run: echo "### Hello world! :rocket:" >> "$GITHUB_STEP_SUMMARY"

      # This step uses GitHub's hello-world-javascript-action
      - name: Hello World
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello

      # This step prints an output (time) from the previous step's action.
      - name: Echo Greeting's Time
        run: echo 'The time was $.'
